language: node_js
node_js:
  - '5.10'
before_install:
 - curl -u${ARTIFACTORY_USERNAME}:${ARTIFACTORY_PASSWORD} https://github.jfrog.io/github/api/npm/auth > ~/.npmrc
 - npm config set registry https://github.jfrog.io/github/api/npm/npm
